In [1]:
###Data Cleanup and Machine Learning

!pip install pandas
!pip install scikit-learn
!pip install numpy
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import joblib
from sklearn import tree
import numpy as np

Requirement already satisfied: pandas in c:\users\reem\appdata\local\programs\python\python313\lib\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\reem\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\reem\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\reem\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\reem\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\reem\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: scikit-learn in c:\users\reem\appdata\local\programs\python\python313\lib\site-packages (1.7.2)
Requirement already satisfied: numpy>=1.22.0 in c:\users\reem\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.3.3)
Requirement already satisfied: scipy>=1.8.0 in c:\users\reem\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.16.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\reem\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\reem\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: numpy in c:\users\reem\appdata\local\programs\python\python313\lib\site-packages (2.3.3)

In [15]:
contact_data = pd.read_csv ('contactsshort.csv')
contact_data.head()

,VANID,Engagement Points As Of Today,Engagement Percentile As Of Today,Engagement Points As Of 7 Days Ago,Engagement Percentile As Of 7 Days Ago,Engagement Points As Of 30 Days Ago,Engagement Percentile As Of 30 Days Ago,Engagement Points As Of 90 Days Ago,Engagement Percentile As Of 90 Days Ago,Engagement Points As Of 1 Year Ago,...,pZip/Postal,pZip4,pCountryCode,pCountryName,pAddressID,Man,Woman,Nonbinary,Notlisted,Prefnoanswer
0,102486007,405,99.0,405,99.0,385,99.0,345,99.0,165,...,10301.0,2627.0,US,United States,901707.0,NaN,x,NaN,NaN,NaN
1,102491589,30,87.0,30,87.0,30,87.0,30,87.0,30,...,11215.0,4623.0,US,United States,906889.0,NaN,x,NaN,NaN,NaN
2,102503625,30,87.0,30,87.0,30,87.0,30,87.0,30,...,20009.0,4809.0,US,United States,917885.0,NaN,x,NaN,NaN,NaN
3,102237946,5,22.0,5,22.0,5,22.0,5,23.0,0,...,7950.0,1747.0,US,United States,692686.0,NaN,x,NaN,NaN,NaN
4,102472556,160,98.0,160,98.0,160,98.0,160,98.0,160,...,11216.0,1851.0,US,United States,884295.0,NaN,x,NaN,NaN,NaN

In [16]:
#fill null with 'na' value
contact_data = contact_data.fillna('na')
contact_data.head()

,VANID,Engagement Points As Of Today,Engagement Percentile As Of Today,Engagement Points As Of 7 Days Ago,Engagement Percentile As Of 7 Days Ago,Engagement Points As Of 30 Days Ago,Engagement Percentile As Of 30 Days Ago,Engagement Points As Of 90 Days Ago,Engagement Percentile As Of 90 Days Ago,Engagement Points As Of 1 Year Ago,...,pZip/Postal,pZip4,pCountryCode,pCountryName,pAddressID,Man,Woman,Nonbinary,Notlisted,Prefnoanswer
0,102486007,405,99.0,405,99.0,385,99.0,345,99.0,165,...,10301.0,2627.0,US,United States,901707.0,na,x,na,na,na
1,102491589,30,87.0,30,87.0,30,87.0,30,87.0,30,...,11215.0,4623.0,US,United States,906889.0,na,x,na,na,na
2,102503625,30,87.0,30,87.0,30,87.0,30,87.0,30,...,20009.0,4809.0,US,United States,917885.0,na,x,na,na,na
3,102237946,5,22.0,5,22.0,5,22.0,5,23.0,0,...,7950.0,1747.0,US,United States,692686.0,na,x,na,na,na
4,102472556,160,98.0,160,98.0,160,98.0,160,98.0,160,...,11216.0,1851.0,US,United States,884295.0,na,x,na,na,na

In [17]:
#replacing x value for gender with yes or no
contact_data['Man'] = contact_data['Man'].str.replace('x','yes')
contact_data['Man'] = contact_data['Man'].str.replace('na','no')
contact_data['Woman'] = contact_data['Woman'].str.replace('x','yes')
contact_data['Woman'] = contact_data['Woman'].str.replace('na','no')
contact_data['Nonbinary'] = contact_data['Nonbinary'].str.replace('x','yes')
contact_data['Nonbinary'] = contact_data['Nonbinary'].str.replace('na','no')
contact_data['Notlisted'] = contact_data['Notlisted'].str.replace('x','yes')
contact_data['Notlisted'] = contact_data['Notlisted'].str.replace('na','no')
contact_data['Prefnoanswer'] = contact_data['Prefnoanswer'].str.replace('x','yes')
contact_data['Prefnoanswer'] = contact_data['Prefnoanswer'].str.replace('na','no')
contact_data.head()

,VANID,Engagement Points As Of Today,Engagement Percentile As Of Today,Engagement Points As Of 7 Days Ago,Engagement Percentile As Of 7 Days Ago,Engagement Points As Of 30 Days Ago,Engagement Percentile As Of 30 Days Ago,Engagement Points As Of 90 Days Ago,Engagement Percentile As Of 90 Days Ago,Engagement Points As Of 1 Year Ago,...,pZip/Postal,pZip4,pCountryCode,pCountryName,pAddressID,Man,Woman,Nonbinary,Notlisted,Prefnoanswer
0,102486007,405,99.0,405,99.0,385,99.0,345,99.0,165,...,10301.0,2627.0,US,United States,901707.0,no,yes,no,no,no
1,102491589,30,87.0,30,87.0,30,87.0,30,87.0,30,...,11215.0,4623.0,US,United States,906889.0,no,yes,no,no,no
2,102503625,30,87.0,30,87.0,30,87.0,30,87.0,30,...,20009.0,4809.0,US,United States,917885.0,no,yes,no,no,no
3,102237946,5,22.0,5,22.0,5,22.0,5,23.0,0,...,7950.0,1747.0,US,United States,692686.0,no,yes,no,no,no
4,102472556,160,98.0,160,98.0,160,98.0,160,98.0,160,...,11216.0,1851.0,US,United States,884295.0,no,yes,no,no,no

In [18]:
contact_data.columns

Index(['VANID', 'Engagement Points As Of Today',
       'Engagement Percentile As Of Today',
       'Engagement Points As Of 7 Days Ago',
       'Engagement Percentile As Of 7 Days Ago',
       'Engagement Points As Of 30 Days Ago',
       'Engagement Percentile As Of 30 Days Ago',
       'Engagement Points As Of 90 Days Ago',
       'Engagement Percentile As Of 90 Days Ago',
       'Engagement Points As Of 1 Year Ago',
       'Engagement Percentile As Of 1 Year Ago',
       'Engagement Points As Of 2 Years Ago',
       'Engagement Percentile As Of 2 Years Ago', 'pAddress', 'pCity',
       'pState/Province', 'pZip/Postal', 'pZip4', 'pCountryCode',
       'pCountryName', 'pAddressID', 'Man', 'Woman', 'Nonbinary', 'Notlisted',
       'Prefnoanswer'],
      dtype='object')

In [19]:
contact_data['Gender'] = None
contact_data['State_value'] = None
contact_data['gender_value'] = None

In [20]:
contact_data.columns

Index(['VANID', 'Engagement Points As Of Today',
       'Engagement Percentile As Of Today',
       'Engagement Points As Of 7 Days Ago',
       'Engagement Percentile As Of 7 Days Ago',
       'Engagement Points As Of 30 Days Ago',
       'Engagement Percentile As Of 30 Days Ago',
       'Engagement Points As Of 90 Days Ago',
       'Engagement Percentile As Of 90 Days Ago',
       'Engagement Points As Of 1 Year Ago',
       'Engagement Percentile As Of 1 Year Ago',
       'Engagement Points As Of 2 Years Ago',
       'Engagement Percentile As Of 2 Years Ago', 'pAddress', 'pCity',
       'pState/Province', 'pZip/Postal', 'pZip4', 'pCountryCode',
       'pCountryName', 'pAddressID', 'Man', 'Woman', 'Nonbinary', 'Notlisted',
       'Prefnoanswer', 'Gender', 'State_value', 'gender_value'],
      dtype='object')

In [21]:
# look for distinct values in state columns to make sure they all have an assigned value

In [22]:
state_num = {state: i + 1 for i, state in enumerate(['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY', 'DC'])}
contact_data.head()

,VANID,Engagement Points As Of Today,Engagement Percentile As Of Today,Engagement Points As Of 7 Days Ago,Engagement Percentile As Of 7 Days Ago,Engagement Points As Of 30 Days Ago,Engagement Percentile As Of 30 Days Ago,Engagement Points As Of 90 Days Ago,Engagement Percentile As Of 90 Days Ago,Engagement Points As Of 1 Year Ago,...,pCountryName,pAddressID,Man,Woman,Nonbinary,Notlisted,Prefnoanswer,Gender,State_value,gender_value
0,102486007,405,99.0,405,99.0,385,99.0,345,99.0,165,...,United States,901707.0,no,yes,no,no,no,None,None,None
1,102491589,30,87.0,30,87.0,30,87.0,30,87.0,30,...,United States,906889.0,no,yes,no,no,no,None,None,None
2,102503625,30,87.0,30,87.0,30,87.0,30,87.0,30,...,United States,917885.0,no,yes,no,no,no,None,None,None
3,102237946,5,22.0,5,22.0,5,22.0,5,23.0,0,...,United States,692686.0,no,yes,no,no,no,None,None,None
4,102472556,160,98.0,160,98.0,160,98.0,160,98.0,160,...,United States,884295.0,no,yes,no,no,no,None,None,None

In [23]:
contact_data['State_value'] = contact_data['pState/Province'].map(state_num)
contact_data.head()

,VANID,Engagement Points As Of Today,Engagement Percentile As Of Today,Engagement Points As Of 7 Days Ago,Engagement Percentile As Of 7 Days Ago,Engagement Points As Of 30 Days Ago,Engagement Percentile As Of 30 Days Ago,Engagement Points As Of 90 Days Ago,Engagement Percentile As Of 90 Days Ago,Engagement Points As Of 1 Year Ago,...,pCountryName,pAddressID,Man,Woman,Nonbinary,Notlisted,Prefnoanswer,Gender,State_value,gender_value
0,102486007,405,99.0,405,99.0,385,99.0,345,99.0,165,...,United States,901707.0,no,yes,no,no,no,None,32.0,None
1,102491589,30,87.0,30,87.0,30,87.0,30,87.0,30,...,United States,906889.0,no,yes,no,no,no,None,32.0,None
2,102503625,30,87.0,30,87.0,30,87.0,30,87.0,30,...,United States,917885.0,no,yes,no,no,no,None,51.0,None
3,102237946,5,22.0,5,22.0,5,22.0,5,23.0,0,...,United States,692686.0,no,yes,no,no,no,None,30.0,None
4,102472556,160,98.0,160,98.0,160,98.0,160,98.0,160,...,United States,884295.0,no,yes,no,no,no,None,32.0,None

In [24]:
for index, row in contact_data.iterrows():
    if row['Man'] == 'yes':
        contact_data.loc[index, 'Gender'] = 'Man'
    elif row['Woman'] == 'yes':
        contact_data.loc[index, 'Gender'] = 'Woman'
    elif row['Nonbinary'] == 'yes':
        contact_data.loc[index, 'Gender'] = 'Nonbinary'
    elif row['Notlisted'] == 'yes':
        contact_data.loc[index, 'Gender'] = 'Notlisted'
    elif row['Prefnoanswer'] == 'yes':
        contact_data.loc[index, 'Gender'] = 'Prefnoanswer'

In [27]:
#data dictionary for gender: 1=man, 2=woman, 3=nonbinary, 4=notlisted, 5=prefnoanswer
gender_num = {gender: i + 1 for i, gender in enumerate(['Man', 'Woman', 'Nonbinary','Notlisted','Prefnoanswer'])}
contact_data['gender_value'] = contact_data['Gender'].map(gender_num)
contact_data.head()

,VANID,Engagement Points As Of Today,Engagement Percentile As Of Today,Engagement Points As Of 7 Days Ago,Engagement Percentile As Of 7 Days Ago,Engagement Points As Of 30 Days Ago,Engagement Percentile As Of 30 Days Ago,Engagement Points As Of 90 Days Ago,Engagement Percentile As Of 90 Days Ago,Engagement Points As Of 1 Year Ago,...,pCountryName,pAddressID,Man,Woman,Nonbinary,Notlisted,Prefnoanswer,Gender,State_value,gender_value
0,102486007,405,99.0,405,99.0,385,99.0,345,99.0,165,...,United States,901707.0,no,yes,no,no,no,Woman,32.0,2
1,102491589,30,87.0,30,87.0,30,87.0,30,87.0,30,...,United States,906889.0,no,yes,no,no,no,Woman,32.0,2
2,102503625,30,87.0,30,87.0,30,87.0,30,87.0,30,...,United States,917885.0,no,yes,no,no,no,Woman,51.0,2
3,102237946,5,22.0,5,22.0,5,22.0,5,23.0,0,...,United States,692686.0,no,yes,no,no,no,Woman,30.0,2
4,102472556,160,98.0,160,98.0,160,98.0,160,98.0,160,...,United States,884295.0,no,yes,no,no,no,Woman,32.0,2

In [28]:
contact_data.head()

,VANID,Engagement Points As Of Today,Engagement Percentile As Of Today,Engagement Points As Of 7 Days Ago,Engagement Percentile As Of 7 Days Ago,Engagement Points As Of 30 Days Ago,Engagement Percentile As Of 30 Days Ago,Engagement Points As Of 90 Days Ago,Engagement Percentile As Of 90 Days Ago,Engagement Points As Of 1 Year Ago,...,pCountryName,pAddressID,Man,Woman,Nonbinary,Notlisted,Prefnoanswer,Gender,State_value,gender_value
0,102486007,405,99.0,405,99.0,385,99.0,345,99.0,165,...,United States,901707.0,no,yes,no,no,no,Woman,32.0,2
1,102491589,30,87.0,30,87.0,30,87.0,30,87.0,30,...,United States,906889.0,no,yes,no,no,no,Woman,32.0,2
2,102503625,30,87.0,30,87.0,30,87.0,30,87.0,30,...,United States,917885.0,no,yes,no,no,no,Woman,51.0,2
3,102237946,5,22.0,5,22.0,5,22.0,5,23.0,0,...,United States,692686.0,no,yes,no,no,no,Woman,30.0,2
4,102472556,160,98.0,160,98.0,160,98.0,160,98.0,160,...,United States,884295.0,no,yes,no,no,no,Woman,32.0,2

In [29]:
#dropping gender columns and other columns we are not using for the model
contact_data = contact_data.drop(columns=['Man', 
                                          'Woman', 
                                          'Nonbinary', 
                                          'Notlisted', 
                                          'Prefnoanswer',
                                          'VANID', 
                                          'Engagement Points As Of Today', 
                                          'Engagement Percentile As Of Today', 
                                          'Engagement Points As Of 7 Days Ago', 
                                          'Engagement Percentile As Of 7 Days Ago',
                                          'Engagement Points As Of 30 Days Ago', 
                                          'Engagement Percentile As Of 30 Days Ago', 
                                          'Engagement Points As Of 1 Year Ago',
                                          'Engagement Percentile As Of 1 Year Ago',
                                          'Engagement Points As Of 2 Years Ago',
                                          'Engagement Percentile As Of 2 Years Ago', 
                                          'pAddress', 
                                          'pCity', 
                                          'pZip/Postal', 
                                          'pZip4', 
                                          'pCountryCode',
                                          'pCountryName', 
                                          'pAddressID'
                                         ])
contact_data.head()

,Engagement Points As Of 90 Days Ago,Engagement Percentile As Of 90 Days Ago,pState/Province,Gender,State_value,gender_value
0,345,99.0,NY,Woman,32.0,2
1,30,87.0,NY,Woman,32.0,2
2,30,87.0,DC,Woman,51.0,2
3,5,23.0,NJ,Woman,30.0,2
4,160,98.0,NY,Woman,32.0,2

In [37]:
print(contact_data.dtypes)

Engagement Points As Of 90 Days Ago          int64
Engagement Percentile As Of 90 Days Ago     object
pState/Province                             object
Gender                                      object
State_value                                float64
gender_value                                 int64
dtype: object

In [4]:
contact_data['Engagement Percentile As Of 90 Days Ago']=contact_data['Engagement Percentile As Of 90 Days Ago'].astype(str)

NameError: name 'contact_data' is not defined

In [34]:
X = contact_data [['gender_value', 'State_value']]
y = contact_data ['Engagement Points As Of 90 Days Ago']

In [36]:
model = DecisionTreeClassifier()
model.fit(X,y)
model.predict([ ['1', '38'] ])

C:\Users\Reem\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([10])